---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": {{ .Values.ceph.clusterID | quote }},
        "monitors": {{ .Values.ceph.monitors | toJson }}
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: default
